apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
  namespace: task-manager
data:
  DB_HOST: task-db-service
  DB_PORT: "5432"
  DB_NAME: taskdb
  DB_USER: postgres
  PORT: "4000"