apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db
  namespace: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
        - name: task-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: task-manager-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: task-manager-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-manager-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: task-db-service
  namespace: task-manager
spec:
  selector:
    app: task-db
  ports:
    - port: 5432
      targetPort: 5432